version: "3.8"

services:
  api:
    build: ./controller
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  adapter:
    build: ./rust-adapter
    depends_on:
      - api
