[package]
name = "access-control-system"
version = "0.1.0"
edition = "2021"

[features]
default = []
embedded-python = ["dep:pyo3"]

[dependencies]
tokio = { version = "1.50.0", features = ["full"] }
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.18"
dotenvy = "0.15.7"
jsonwebtoken = "10.3.0"
warp = { version = "0.4.2", features = ["websocket", "server"] }
pyo3 = { version = "0.28.2", features = ["auto-initialize"], optional = true }

[target.'cfg(unix)'.dependencies]
serialport = "4.8.1"
