[package]
name = "access-control-system"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1", features = ["derive"] }

thiserror = "2.0.18"
serde_json= "1.0"
tokio-util= { version = "0.7", features = ["codec"] }
bytes= "1.11.1"
anyhow="1.0.101"
chrono ="0.4"
panic-halt = "1.0.0"
